(ns kancolle-clj.api
  (:use [kancolle-clj.core]))

(def get-basic (create-api-call "/api_get_member/basic"))
(def get-record (create-api-call "/api_get_member/record"))
(def get-mapinfo (create-api-call "/api_get_master/mapinfo"))
(def login-check (create-api-call "/api_auth_member/logincheck"))
(def get-ndock (create-api-call "/api_get_member/ndock"))
(def get-ship2 (create-api-call "/api_get_member/ship2"))
(def speed-change (create-api-call "/api_req_nyukyo/speedchange"))
(def get-material (create-api-call "/api_get_member/material"))
(def start-recovery (create-api-call "/api_req_nyukyo/start"))
(def get-ship (create-api-call "/api_get_member/ship"))
(def actionlog (create-api-call "/api_get_member/actionlog"))
(def charge (create-api-call "/api_req_hokyu/charge"))
(def battle-start (create-api-call "/api_req_map/start"))
(def battle (create-api-call "/api_req_sortie/battle"))
(def battle-result (create-api-call "/api_req_sortie/battleresult"))
(def slotitem (create-api-call "/api_get_member/slotitem"))
(def deck (create-api-call "/api_get_member/deck"))
(def deck-port (create-api-call "/api_get_member/deck_port"))
